package exception;

public class Use_of_throw_ {
	public static void main(String[] args) {
		System.out.println("hii");
		
		throw new ArithmeticException();
	}

}
